name: Docker Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
    - name: Send email notification
      if: success()  # Only runs if the build is successful
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.gmail.com  # Correct SMTP server address for Gmail
          server_port: 587  # Port for Gmail SMTP server
          username: ${{ secrets.GMAIL_USERNAME }}  # Gmail username (your Gmail email)
          password: ${{ secrets.GMAIL_APP_PASSWORD }}  # Gmail app password (not regular password)
          from: ${{ secrets.GMAIL_USERNAME }}  # Sender email (same as the username)
          to: "bharghav588@gmail.com"  # Recipient's email
          subject: "Build Successful"
          body: "The build for your repository has completed successfully!!!"
