name: Docker Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Install msmtp
      run: |
        sudo apt-get update
        sudo apt-get install msmtp msmtp-mta

    - name: Send email notification
      if: success()  # Only runs if the build is successful
      run: |
        echo "The build for your repository has completed successfully!" | msmtp --host=email-smtp.us-east-1.amazonaws.com \
          --port=587 \
          --auth=on \
          --user="${{ secrets.AWS_SES_SMTP_USERNAME }}" \
          --password="${{ secrets.AWS_SES_SMTP_PASSWORD }}" \
          --from="${{ secrets.GMAIL_USERNAME }}" \
          --to="bharghav588@gmail.com" \
          --subject="Build Successful"
