name: Docker Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Send email notification using SES
      if: success()  # Only runs if the build is successful
      run: |
        aws ses send-email \
          --from "${{ secrets.GMAIL_USERNAME }}" \
          --destination "ToAddresses=bharghav588@gmail.com" \
          --message "Subject={Data=Build Successful,Charset=utf8},Body={Text={Data=The build for your repository has completed successfully!,Charset=utf8}}" \
          --region us-east-1
